// Role IDs come from agent/characters/index.ts; nicknames describe visual avatars only.
export const ROSTER = [
  {
    id: "orchestrator",
    role: "Lead",
    name: "Артём",
    model: "kai",
    responsibility: "Координация команды и делегирование",
    x: -5.8,
    z: -6.95,
    accent: "#54796c",
  },
  {
    id: "pm",
    role: "PM",
    name: "Аня",
    model: "mira",
    responsibility: "Задачи, сроки и риски",
    x: -1.65,
    z: -6.95,
    accent: "#a77967",
  },
  {
    id: "product",
    role: "Product",
    name: "Даня",
    model: "leo",
    responsibility: "Ценность продукта, сценарии и приоритеты",
    x: 2.5,
    z: -6.95,
    accent: "#657f9d",
  },
  {
    id: "backend",
    role: "Backend",
    name: "Никита",
    model: "noah",
    responsibility: "API, данные и бизнес-логика",
    x: -1.65,
    z: -2.75,
    accent: "#527581",
  },
  {
    id: "frontend",
    role: "Frontend",
    name: "Соня",
    model: "nika",
    responsibility: "Интерфейс, React и доступность",
    x: -5.8,
    z: -2.75,
    accent: "#618260",
  },
  {
    id: "tgdev",
    role: "TG-Dev",
    name: "Дима",
    model: "ren",
    responsibility: "Telegram-боты, MTProto и Mini Apps",
    x: 2.5,
    z: -2.75,
    accent: "#ad6253",
  },
  {
    id: "aieng",
    role: "AI Eng",
    name: "Макс",
    model: "omar",
    responsibility: "LLM, инструменты, RAG и оценки",
    x: -5.8,
    z: 1.45,
    accent: "#578b90",
  },
  {
    id: "qa",
    role: "QA",
    name: "Ева",
    model: "eva",
    responsibility: "Тестирование и регрессии",
    x: -1.65,
    z: 1.45,
    accent: "#818771",
  },
  {
    id: "smm",
    role: "SMM",
    name: "Алина",
    model: "luna",
    responsibility: "Социальные каналы и аналитика",
    x: 2.5,
    z: 1.45,
    accent: "#659678",
  },
  {
    id: "copy",
    role: "Copy",
    name: "Илья",
    model: "jules",
    responsibility: "Тексты, редактура и контент",
    x: -5.8,
    z: 5.65,
    accent: "#6b87a1",
  },
  {
    id: "design",
    role: "Design",
    name: "Маша",
    model: "mei",
    responsibility: "Дизайн продукта и визуальная система",
    x: -1.65,
    z: 5.65,
    accent: "#986e84",
  },
  {
    id: "perm",
    role: "Permissions",
    name: "Саша",
    model: "alex",
    responsibility: "Проверка действий и разрешений",
    x: 2.5,
    z: 5.65,
    accent: "#917c5a",
  },
] as const;
export type Member = (typeof ROSTER)[number];
export type RoleId = Member["id"];
export const ROOM = { half: 10, limit: 9.6 };
export function seatNumber(id: RoleId) {
  return String(ROSTER.findIndex((m) => m.id === id) + 1).padStart(2, "0");
}
